### PR TITLE
update many dependencies

### PR DESCRIPTION
**Pull request by felixhao28**
and fix the broken bin/pegcoffee.coffee.

### CODE REVIEW

**Comment by keis** [comment]
Hi @Dignifiedquire would be great if this could get merged

**Comment by Dignifiedquire** [comment]
Thanks sorry for not reviewing earlier will try to merge soon

**Comment by ryoqun** [comment]
@dignifiedquire Hi! Thanks for creating this npm package! Any chance this gets to be merged? :)

**Comment by dignifiedquire** [comment]
Thank you and sorry for the delay

**Comment by felixhao28** [comment]
Well a whole year has passed and I assume dependencies got outdated once again.

**Comment by ryoqun** [comment]
@dignifiedquire Thanks! :)

@felixhao28 that's true. btw, I'm just started to hacking on the pegjs thingy.. if I decide to use it seriously, maybe I can lend my hand for the update... :)

**Pull request merged**
